### ISSUE TITLE
Node v16 or higher support?

### ISSUE THREAD

**Issue by cangSDARM** [elmarx/nodejs-sys#15]
I used node with v16.13.0. And I think those `n-api` changed. Because my link failed with 1120 (*.lib not found).

![image](https://user-images.githubusercontent.com/20441896/151652801-f8ab1269-6a29-426a-8eea-f5a65a24b29e.png)

**Comment by elmarx** [comment]
Hey there,

The N-API did not change between v15.12.0 (the last node version this crate has been published for) and v16.13.0, as you may check when running `git diff --name-only v15.12.0..v16.13.0 src/node_api.h src/js_native_api.h src/js_native_api_types.h src/node_api_types.h` in the nodejs sources.

**Comment by cangSDARM** [comment]
Thanks, I'll check again

**Comment by elmarx** [comment]
Assuming this is done :)
