### ISSUE TITLE
Bump bindgen version and publish

### ISSUE THREAD

**Issue by kjvalencik** [elmarx/nodejs-sys#18]
👋 If possible, I would appreciate a bump of `bindgen` and a publish to eliminate `ansi_term` from the dependency tree (transitive dependency from `bindgen`'s use of `clap`).

Thanks!

**Comment by elmarx** [comment]
Sure, will do :)

**Comment by elmarx** [comment]
https://crates.io/crates/nodejs-sys/0.14.0

Closing for now, if anything is left todo, just reopen/open a new one :)
